version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmqhost
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mddplatform

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongohost
    ports:
      - 27017:27017
    networks:
      - mddplatform

  plantuml-service:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-service
    ports:
      - 8080:8080
    networks:
      - mddplatform
  
networks:
  mddplatform:
    name: mddplatform
    external: true
